default_context:
  project_id: "my-google-project-id"
  domain_name: "mydomain.com"
  gcp_user_account: "me@gmail.com"
  state_bucket: "my-terraform-state-bucket"
  pcg_bucket_name: "pcg_bucket_name"
  global_server: "global.mydomain.com"
  materialize_datastack: "myfirstdatastack"
  region: "us-west1"
  zone: "us-west1-b"
  owner: "cave"
  local_environment_name: "local"
  local_cluster_prefix: "local1"
  local_sql_instance_name: ""
  dns_zone: ""
  vpc_name_override: "daf-api3-network"
  pcg_redis_name_override: "v1dd-pcg-cache"
  bigtable_google_project: ""
  skeleton_cache_cloudpath: "gs://pcg_skeleton_bucket"
  pcg_skeleton_cache_bucket_public_read: "false"
  bigtable_instance_name: "pychunkedgraph"
  docker_registry: "docker.io/caveconnectome"
  cave_secret_name: "my-cave-secret"
  letsencrypt_email: "me@gmail.com"
  materialization_dump_bucket_name: "cave_materialization_bucket/public"
  materialization_upload_bucket_name: "cave_materialization_bucket"