default_context:
  repo_name: "cave-terraform-env"
  project_id: "em-270621"
  domain_name: "em.brain.allentech.org"
  gcp_user_account: "forrestc@alleninstitute.org"
  state_bucket: "a12345198-terraform-state"
  pcg_bucket_name: "v1dd_pcg"
  global_server: "global.em.brain.allentech.org"
  materialize_datastack: "v1dd"
  region: "us-west1"
  zone: "us-west1-b"
  owner: "cave"
  local_environment_name: "allen"
  local_cluster_prefix: "api6"
  local_sql_instance_name: "em-api3"
  dns_zone: "em"
  vpc_name_override: "daf-api3-network"
  pcg_redis_name_override: "v1dd-pcg-cache"
  bigtable_google_project: ""
  skeleton_cache_cloudpath: "gs://v1dd_pcg/pcg_skeletons"
  pcg_skeleton_cache_bucket_public_read: "true"
  bigtable_instance_name: "pychunkedgraph"
  docker_registry: "docker.io/caveconnectome"
  cave_secret_name: "allen-cave-token"
  letsencrypt_email: "forrestc@alleninstitute.org"
  materialization_dump_bucket_name: "cave_annotation_bucket/public"
  materialization_upload_bucket_name: "cave_annotation_bucket"