# skeletoncache default values generated by Terraform
skeletoncache:
  # Default to the SkeletonService SA secret created by Terraform
  credentialsSecret: "${skeleton_sa_secret}"
  # Optional: full gs:// path (bucket and prefix) for SKELETON_CACHE_BUCKET
  cloudPath: "${skeleton_cache_cloudpath}"
