#!/usr/bin/env bash
set -euo pipefail

# This script is generated by Terraform. Do not edit.
# Injected variables:
#   project:     ${project_id}
#   region:      ${region}
#   zone:        ${zone}
#   sql_instance_name: ${sql_instance_name}

# Run from the helmfile directory generated by Terraform
cd "$(dirname "$0")"

need() { command -v "$1" >/dev/null 2>&1 || { echo "Missing dependency: $1" >&2; exit 1; }; }
need gcloud
need kubectl
need helm
need helmfile
need jq

echo "Setting gcloud project: ${project_id}"
gcloud config set project "${project_id}" >/dev/null

docker pull gcr.io/cloudsql-docker/gce-proxy:1.16
docker rm --force gce-proxy
docker rm --force adminer
docker run -d \
-v $HOME/.config/gcloud/:/config \
  -p 127.0.0.1:3306:3306 \
  --name gce-proxy \
  gcr.io/cloudsql-docker/gce-proxy:1.16 /cloud_sql_proxy \
  -instances=${project_id}:${region}:${sql_instance_name}=tcp:0.0.0.0:3306 -credential_file=/config/application_default_credentials.json
docker run --link gce-proxy:db -p 8080:8080 --name adminer adminer

echo "cloud sql running on local port 3306, adminer on port 8080"

# Fetch DB credentials from Secret Manager at runtime so they are never baked
# into this generated script. The secret payload is a JSON object with
# "username" and "password" keys (same source vals resolves for helm as
# ref+gcpsecrets://${project_id}/${postgres_credentials}#username).
creds="$(gcloud secrets versions access latest \
  --secret="${postgres_credentials}" \
  --project="${project_id}")"

echo "connect to adminer at http://localhost:8080 with:"
echo "  system:   PostgreSQL"
echo "  server:   db"
echo "  username: $(jq -r '.username' <<<"$${creds}")"
echo "  password: $(jq -r '.password' <<<"$${creds}")"
