# landingpage default values generated by Terraform.
# The service list ships as the chart default (charts/landingpage/values.yaml);
# this file only carries the per-environment identity. Override services in a
# landingpage.yaml next to this file if a deployment needs a different set.
landingpage:
  title: "${environment} - CAVE"
  heading: "CAVE services on ${environment}"
  subheading: "Connectome Annotation Versioning Engine services running on this deployment."
