# pcgl2cache default values generated by Terraform
pcgl2cache:
  bigtable:
    instance: "${bigtable_instance}"
  credentialsSecret: "${pycg_sa_secret}"
  googleSecretFilename: "google-secret.json"
  caveSecretFilename: "cave-secret.json"
  secretFiles:
    - name: google-secret.json
      value: "ref+gcpsecrets://${secrets_project_id}/${pycg_sa_secret}"
    - name: cave-secret.json
      value: "ref+gcpsecrets://${secrets_project_id}/${cave_secret_name}"
  # Subscription names come from the local_cluster module outputs (single source of truth).
  queues:
    update: "${l2cache_worker_subscription}"
    high: "${l2cache_high_trigger}"
    low: "${l2cache_low_trigger}"
  # Default exchanges
  exchanges:
    update: "${cluster_prefix}_L2CACHE"
    # Edits exchange shared with PCG; aligns with PYCHUNKEDGRAPH_EDITS_EXCHANGE
    edits: "${cluster_prefix}_PCG_EDIT"
