materialize:
  # Reference the scaffolded schedules.json via Helmfile file ref
  schedules: "ref+file://schedules.json"
  maxDatabases: 3
  minDatabases: 1
  datastacks:
    - {{ cookiecutter.materialize_datastack }}